### ISSUE TITLE
Provide a code snippet for refreshing all exiting packages with newer versions from public pypi.python.org

### ISSUE THREAD

**Issue by ssbarnea** [pypiserver/pypiserver#135]
It would extremely helpful if we could have a small example (probably in bash) that could be used to refresh all the local packages with newer versions from pypi.python.org.

People could put this in a cronjob or make a Jenkins job that is run on demand, probably at the end of the sprint.

**Comment by bibby** [comment]
project [bandersnatch](https://pypi.python.org/pypi/bandersnatch) may be more suitable to mirror pypi packages, [according to pypi](https://pypi.python.org/mirrors).

**Comment by mplanchard** [comment]
@ssbarnea we already provide output of the commands necessary for upgrading packages with the `-U` option on the pypiserver. I suppose I could write an example of how to take the output of that and pass it through xargs or something to go ahead and run all those commands.

**Comment by ankostis** [comment]
This probably moves to next release?

**Comment by mplanchard** [comment]
Agreed. I have not found the time to get to this, but I will ensure it gets done when I get back from vacation.

**Comment by mplanchard** [comment]
I know it's been a while on this one, but I don't feel like this is anything that needs to be addressed. 

See this particular line from the docs: 
> After that it shows a *pip* command line which can be used
to update a one package. Either copy and paste that or run
``pypi-server -Ux`` in order to really execute those commands.

@ssbarnea I believe that is exactly what you need. I'm going to close this now. Please feel free to reply if that functionality isn't working or is not what you need.
