### ISSUE TITLE
option to specify application base URL

### ISSUE THREAD

**Issue by luismsgomes** [pypiserver/pypiserver#155]
Started pypiserver on port 127.0.0.1:8001 as follows:

```
$HOME/.pyenv/shims/pypi-server \
  --interface 12.0.0.1 --port 8001 \
  --authenticate update,download \
  --passwords $HOME/pypiserver/htpasswd.txt \
  --log-file $HOME/pypiserver/log.txt -vv \
  $HOME/pypiserver/packages
```

Then tried to reverse proxy the application through apache as follows:

```
ProxyPass  "/pypi/"  "http://127.0.0.1:8001/"
```

I can access the welcome page at the front-facing address `/pypi/` but the URLs in that page are wrong:
`/simple` should be `/pypi/simple`

Is it possible to add an option to `pypi-server --app-root=/pypi/` so that all URLs are prefixed with the given URL?

**Comment by ankostis** [comment]
Unfortunately this is not as simple as it sounds since all urls are affected (see also #100 & #123).
Maybe a better configuration is to use `mod_wsgi` as described [in the document](/pypiserver/pypiserver#apache-mod-wsgi).
That way you get also multi-threaded responses for free.

Please provide some feedback if you attemt to setup it up.
