### ISSUE TITLE
Remove outdated nginx docs, add instructions for proxy_cache

### ISSUE THREAD

**Issue by RiceKab** [pypiserver/pypiserver#232]
### Context Summary

As mentioned in [the documentation](https://pypi.org/project/pypiserver/#serving-thousands-of-packages ) one option to increase performance is to serve packages from behind a static webserver.

The problem is that this requires the directory structure to have the structure conforming to [PEP 503](https://www.python.org/dev/peps/pep-0503/) which is not the default behaviour for uploading files.

### Example

Imagine we are serving the following packages directory:

```
packages
    |-- alpha
            |-- alpha-1.0.0.tar.gz
    |-- bravo
            |-- bravo-1.0.0.tar.gz
    |-- charlie-1.0.0.tar.gz
```

Pypiserver is running with ´pypi-server -P .htaccess -p 8080 /path/to/packages´

Nginx is configured to serve this with autoindex:

```
# server listening on 8080
location /packages {
    alias /path/to/packages;
    autoindex on;
}
```

Installing works for all 3 packages when using `localhost:8080/simple` (pypiserver) but will fail for the `charlie` package when using `localhost:8080/packages` (nginx)

The problem arises from the fact that uploading to pypiserver places files in the package root instead of into an appopriate subdirectory. This causes autoindex to not properly generate the correct structure with regards to PEP 503.

So `twine upload --repository-url http://localhost:8080 --skip-existing dist/delta-1.0.0.tar.gz` will place it in `packages/delta-1.0.0.tar.gz` instead of `packages/delta/delta-1.0.0.tar`.

---

Am I doing something wrong with my nginx configuration? Perhaps I'm missing some option in pypiserver? For now I've resorted to automatically moving them into subfolders in intervals but that's not a very clean solution.

---

Related issue #34

**Comment by mplanchard** [comment]
Thanks for the detailed report! Sorry for the delayed response. I didn't get on the computer much over the holiday.

The problem you're running into is that the directory structure doesn't need to (and doesn't) map to the URL structure. PEP 503 says

> Below the root URL is another URL for each individual project contained within a repository. The format of this URL is /<project>/ where the <project> is replaced by the normalized name for that project, so a project named "HolyGrail" would have an URL like /holygrail/

> There is no constraints on where the files must be hosted relative to the repository

We store all of the package files in a single directory. This helps to save a fair bit of complexity on the server side. But, we do serve packages via the `/simple/package_name` interface.

So, we do conform to PEP 503. However, things get confusing when trying to serve the content directly from the filesystem via nginx, and tbh I'm not even sure that section should be in the documentation anymore. I can't say that I've ever tried serving packages that way, and I'm not sure that there's a good way to make it work. It's possible that pip used to look in the root directory rather than using the newer simple index API (which automatically looks for `project_name/project_file`), but it certainly doesn't now, which leads to confusing behavior like this. 

Anyway, all that is to say that I think this is a fundamental limitation of trying to serve straight from the filesystem, given that we (for good reasons) use a flat structure for our actual file store. 

One possible alternative to serving packages directly would be to use nginx as a reverse proxy and enable the cache within your proxy configuration as described [here](https://www.nginx.com/blog/nginx-caching-guide/). At a previous job, we were serving upwards of 1000 downloads/min with that type of configuration and a 10 GB cache. This would allow you to use pypiserver's uploads (which make use of a flat structure), while still gaining the performance boost of nginx. This would keep the URL interface (provided by pypiserver) separate from the filesystem, as it should be.

I will rename this task to remind me that I need to remove that confusing bit of documentation and replace it with a better description of using the proxy cache.

In the meantime, if you get a nice configuration going with that and would like to share it here, I'll include it in the docs. It would save me from having to get one set up and tested locally, which would be nice, since I don't have access to the configuration we used at my previous job anymore.

**Comment by RiceKab** [comment]
I'll try and get around to doing some testing for it this weekend.
