### ISSUE TITLE
docker image gives error No such file or directory: '/home/pypiserver/packages'

### ISSUE THREAD

**Issue by predicador37** [pypiserver/pypiserver#243]
Hi:
I'm trying to run pypiserver from the image uploaded to the Dockerhub, but it always shows this error:

` Error: while trying to list root(/home/pypiserver/packages): [Errno 2] No such file or directory: '/home/pypiserver/packages'`

The docker command I'm using is:

`sudo docker run --name pypiserver -p 8080:8080 pypiserver/pypiserver:latest -d pypiserver`

Any ideas? Thanks in advance.

**Comment by mplanchard** [comment]
heyo! 

The Dockerfile creates a persistent volume at `/data/packages`, and by default tries to serve packages from there:

```
VOLUME /data/packages
USER pypiserver
WORKDIR /data
EXPOSE 8080

ENTRYPOINT ["pypi-server", "-p", "8080"]
CMD ["packages"]
```

Passing `pypiserver` as the final argument to `docker run` is replacing the `CMD` for your container instance:

```
docker run --help

Usage:	docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
```

and so is passing that argument to the `ENTRYPOINT`.

That being said, I get a different error from you when I do the same:

```
docker run --rm pypiserver/pypiserver:latest pypiserver
Error: while trying to list root(/data/pypiserver): [Errno 2] No such file or directory: '/data/pypiserver'
```

Could you verify you're on the most recently tagged `latest` with `docker pull pypiserver/pypiserver:latest`? With that, you should get the same error message as I pasted above.

To avoid getting any error message at all, you can either run without the final `pypiserver`, which will serve packages from the persistent docker volume at `/data/packages` in the container, or you can adjust the command as needed. You can see an example in [the docs](https://github.com/pypiserver/pypiserver#using-the-docker-image) and the example [docker-compose file](https://github.com/pypiserver/pypiserver/blob/master/docker-compose.yml). There's also a real functional example in the [testing script](https://github.com/pypiserver/pypiserver/blob/master/bin/test-docker.sh) that gets run as part of our testing pipeline.

Let me know if you run into any issues or have more questions!

**Comment by predicador37** [comment]
Gosh... my fault! You're completely right. I have it running now, vesrion 1.2.7.

Thanks a lot and sorry for bothering you!

**Comment by mplanchard** [comment]
No worries! I always prefer these kinds of issues to ones that mean I have to fix something 😊

**Comment by predicador37** [comment]
Nevertheless, I've had problems with directory permissions inside the container. the /data/packages directory was owned by root, not by pypiserver user as the Dockerfile shows. Then I cloned the repo and used docker-compose with the local Dockerfile and everything was OK. I checked that the pulled image from Dockerhub was the last one (1.2.7, uploaded 14 days ago). Maybe it is not really the most up to date image?

Thanks in advance

**Comment by mplanchard** [comment]
Hmmm. It's possible that the volume was created by the old image and maintained through to the new one, including its permissions.

If you've got the time, could you verify that everything behaves properly if you first remove all containers, images, and volumes, and then pull fresh? Something like the following commands:

```
docker container ls -a | grep pypiserver | awk '{print $1}' | xargs docker container rm -f
docker image ls -a | grep pypiserver | awk '{print $3}' | xargs docker image rm -f 
docker volume prune

docker pull pypiserver/pypiserver:latest
```

**Comment by jetheurer** [comment]
Should *tar.gz files be placed in the data/packages directory?

**Comment by mplanchard** [comment]
@jetheurer by default pypiserver serves packages from the persistent `/data/packages` directory inside the container, so if you run the container, and then upload a package, you should see it reflected in the running container with `docker-compose exec pypiserver ls /data/packages`.

You wouldn't see them using `docker-compose run` because that starts up a new container instance, which will have its own persistent volume space (unless you've configured it differently in your compose file).

If you'd like to mount packages on your host filesystem into the container, you'll need to extend our [example docker-compose config](https://github.com/pypiserver/pypiserver/blob/master/docker-compose.yml), a bit. This is because the pypiserver Dockerfile sets up a volume at `/data/packages` (so that it will be persisted in the default setup). The example config mounts a bind volume at `/data`, but this does not override the mount at `/data/packages`, so your host `./data/packages` directory won't reflect the container `/data/packages` directory. The way to resolve this is to explicitly mount `./data/packages` to `/data/packages`

So if my compose file looks like this:

```yaml
version: "3.3"

services:
    pypiserver:
        image: pypiserver/pypiserver:latest
        volumes:
            - type: bind
              source: ./data/packages
              target: /data/packages
            - type: bind
              source: ./data
              target: /data
        ports:
            - "80:8080"
```

and it's in a directory that looks like this:

```
/pypiserver
  /data
    /packages
      pypiserver-1.2.7-py2.py3-none-any.whl
  docker-compose.yml
```

If I `cd pypiserver && docker-compose up`, it will start `pypiserver` serving those packages:

```
[1] mplanchard@planchard-home ~/github/pypiserver/pypiserver $
docker-compose up
Recreating pypiserver_pypiserver_1 ... done
Attaching to pypiserver_pypiserver_1
```

I can verify this from another terminal:

```
[0] mplanchard@planchard-home ~/github/pypiserver/pypiserver $
docker-compose exec pypiserver ls packages
pypiserver-1.2.7-py2.py3-none-any.whl

[0] mplanchard@planchard-home ~/github/pypiserver/pypiserver $
pip3 search --index http://localhost:80 pypiserver
pypiserver (1.2.7)  - 1.2.7
```

I definitely think the docs could be clearer on this point! I'll update the composefile example with some more details. Please let me know if this resolves your issue or if you have any questions!

**Comment by mplanchard** [comment]
Actually, the comment in the compose file is dead wrong!

> # Use an .htpasswd file to control access, serve packages from ./data (which will be /data in the container)

Sorry about the confusion. Working on an update now
