### ISSUE TITLE
server error when serving a  lot of packages

### ISSUE THREAD

**Issue by gadh** [pypiserver/pypiserver#246]
i use packages dir on a  with 150K packages, the server seems to load fine but every connection to it is broken - even to its homepage

**Comment by mplanchard** [comment]
Sorry you’re having this issue!

Have you verified that your server works when you have fewer packages?

I suspect we may be running into available memory issues.

**Comment by skruger** [comment]
I think this is an inevitable part of how pypi server works. I had similar problems with mine and I ended up solving it by decorating digest_file, listdir, and find_packages in pypiserver.core and implementing some caching in my custom decorators.

Because pypiserver doesn't have a metadata database it has to scan the filesystem for every request.

**Comment by mplanchard** [comment]
Have y'all tried the caching solution described in the README? https://github.com/pypiserver/pypiserver#serving-thousands-of-packages

**Comment by pawamoy** [comment]
I'd suggest closing for lack of answers from participants, and also because a solution is provided in the readme, as pointed out by @mplanchard.

**Comment by dee-me-tree-or-love** [comment]
Thanks, totally true @pawamoy, closing
