### ISSUE TITLE
How to increase max package size when using docker

### ISSUE THREAD

**Issue by pinkynrg** [pypiserver/pypiserver#279]
Currently I get:

```
Submitting dist/test-2019.10.28.361.tar.gz to https://pypi.facco.net
Upload failed (413): Request Entity Too Large
error: Upload failed (413): Request Entity Too Large
```

**Comment by pinkynrg** [comment]
Sorry it was my reverse proxy the problem.

**Comment by simonvadee** [comment]
for people stumbling across this problem, I had a large package (>1Gb) that could not be uploaded to `pypiserver` due to a `413: request entity too large` even after I edited the `client_max_body_size` setting of my (nginx) reverse proxy.

Turns out the default "bottle" webserver itself has a body size limit:
```
Server 'auto' selected. Expecting bottle to run 'Waitress'. Passing extra keyword args: {}
Bottle v0.12.18 server starting up (using AutoServer())...
Listening on http://0.0.0.0:8080/
```

Maybe you can configure this limit, but I chose to just override the webserver using `--server wsgiref` when launching `pypiserver`.
```
Running bottle with selected server 'wsgiref'
Bottle v0.12.18 server starting up (using WSGIRefServer(handler_class=<class 'pypiserver.__main__.WsgiHandler'>))...
Listening on http://0.0.0.0:8080/
```

and you're good to go!

**Comment by dee-me-tree-or-love** [comment]
@simonvadee thanks a lot for sharing the inisghts! This is a great write-up and hopefully can save other people some trouble. 👍 Don't hesitate to open up a separate issue if these problems persist or seem to be not configuration related.
