### ISSUE TITLE
Use Python 3 in Docker container

### ISSUE THREAD

**Issue by etene** [pypiserver/pypiserver#281]
Hello,

I've noticed the Python version used to run pypiserver in its official Docker container is still 2.7.
Since it reaches EOL soon, would you object to upgrading to Python 3 ?

I'd like to work on this and submit a PR if you're interested. I might base the image on an official Python alpine image like `3.6-alpine`, if you're OK with that.

**Comment by mplanchard** [comment]
Glad you noticed! I would love to accept help on this, and I'm definitely for upgrading the image to use Python 3. Our next major version will probably drop official python 2 support, since it's EoL.

Seems like basing it on the official python alpine image would be totally fine. In general, everything should "just work," since we try to stay well tested and up to date with Python 3.

Don't hesitate to ask if you run into any snags or need any help!

**Comment by etene** [comment]
The official Python Alpine image is bigger than the base Alpine one, I think I can get the image size a bit under 100M by using a multi stage build, but not much smaller. Is that a problem ?

I think that it's cleaner to use the official image, and that the image size trade-off is worth it, but if you see a problem with that I'll switch back.
