### ISSUE TITLE
Consider further clarification about the relationship to PyPI

### ISSUE THREAD

**Issue by Julian** [pypiserver/pypiserver#307]
Hi -- (thanks for making this!)

Would you possibly consider language at the start of the README making it even more clear that this project is not related to PyPI / PyPI.org itself, nor is it what PyPI.org runs?

I've unfortunately seen multiple different folks confused by it and had to explain to them that this project is unrelated (I suspect mostly by the name of the package and not knowing much about PyPI). There already is language in the README saying this package is "PyPI compatible", so one may think that shouldn't happen, and yet as I say it unfortunately seems to in a few cases from folks I've seen.

Thoughts obviously welcome, and happy to send a PR if that's something you may be amenable to -- perhaps saying something like "This package is unrelated to PyPI itself. The pypi.org website, used by pip and other packaging tools by default, is maintained by [PyPA](https://github.com/pypa/), and the specific software used to run it is [warehouse](https://github.com/pypa/warehouse/). This package does however implement the same interface used by the official PyPI, and as such is suitable for self-hosting a seperate server of Python packages."

But maybe others will have an even better idea for how to make that as transparently clear as possible.

**Comment by mplanchard** [comment]
Yeah, absolutely! Always happy to update the docs to make things more clear. The company where I work has been super busy due to the COVID-19 situation, so I've been a bit lax about doing updates here, but I'm happy to review a PR to make it clear that we're not directly associated with PyPI or the Python Packaging Authority. Alternatively, I can get a wording change in when things calm down a bit. Thanks for pointing the issue out!

**Comment by Julian** [comment]
Thanks for the quick response, that's great! Will try to put something together for comments.

(And of course no worries on the business, trust me I understand...)
