### ISSUE TITLE
access log printed to stderr

### ISSUE THREAD

**Issue by jacek-jablonski** [pypiserver/pypiserver#328]
Hi,

I've noticed that access log messages like:
`[31/Jul/2020 18:13:23] "GET / HTTP/1.1" 200 1009`
are printed to stderr. Cloud monitoring systems like stackdriver qualifies these messages as errors, so as you may presume error reports list is polluted.

I've also noticed that there is no simple way to change this behavior. Docs mention `--log-conf` cli parameter, but it isn't used anywhere in code.

Am i missing something or is it a bug?
Cheers.

**Comment by dee-me-tree-or-love** [comment]
Oh, nice catch, thanks, I will try to take a closer look in the near time!

**Comment by dee-me-tree-or-love** [comment]
@jacek-jablonski I've checked out the code base and indeed, logging is not very well managed yet. Related to your question I found that the access logs are handled by `bottle` package itself and there is a [related discussion on StackOverflow](https://stackoverflow.com/questions/28984752/python-flask-writes-access-log-to-stderr). I'll try to check it out and fix up the configuration and the logging setup possibilities. If you will have time and are up for some help in reviewing, would be much obliged!

**Comment by jacek-jablonski** [comment]
> @jacek-jablonski I've checked out the code base and indeed, logging is not very well managed yet. Related to your question I found that the access logs are handled by `bottle` package itself and there is a [related discussion on StackOverflow](https://stackoverflow.com/questions/28984752/python-flask-writes-access-log-to-stderr). I'll try to check it out and fix up the configuration and the logging setup possibilities. If you will have time and are up for some help in reviewing, would be much obliged!

Thanks for information. I'll of course help in testing and reviewing.

**Comment by elfjes** [comment]
It's actually not that difficult. The thing is that when calling `logging.basicConfig()`, a default `StreamHandler` is added to the root logger. by default, a `StreamHandler` logs to `stderr`. Luckily, it's really easy to tell `basicConfig` to use `stdout` instead. PR is coming up.

Testing it is harder though, since pytest messes with the root logger, so `basicConfig` behaves differently during testing. So for now I've tested with `python -m pypiserver -v /tmp 2> >(while read line; do echo -e "\e[01;31m$line\e[0m" >&2; done)` to color output to stderr, which confirms the switch from stderr to stdout

**Comment by dee-me-tree-or-love** [comment]
@elfjes that's really nice, thanks for the quick fix! 
I've checked the merge request, that's indeed a nice find, to make it though compliant with @jacek-jablonski request, could you look into setting it to `stdout` only when specified so in the configs? Otherwise, it will print to stdout at all times, not sure if that's the right approach, right? Correct me if I am wrong of course.  

Also have a suggestion for a test, indeed, testing logging is quite difficult, but you can maybe check using the combination of `patch`es and `mock`s even from `unittest.mock` package (there must be one for `pytest` that is used here too) whether a logger is instantiated with correct parameters at all times. But don't spend too much time if that's not a good idea in your opinion.  

Nice catch anyways!

**Comment by elfjes** [comment]
@dee-me-tree-or-love I've added a configuration option for it and some tests. I've also removed the non-implemented `--log-conf` option from the docs so as to not confuse future people.

Looking further into the logging though, I'm not 100% sure this catches all log messages from all supported wsgi servers. Some of them, like stdlibs `wsgi_ref` seem to write to `stderr` directly, although this should be overridable. I haven't extensively looked at all supported wsgi servers, although most seem to use the `logging` module
