### ISSUE TITLE
Convert README to markdown

### ISSUE THREAD

**Issue by mplanchard** [pypiserver/pypiserver#366]
We used to have to do python project READMEs as restructured text files, because that was all that was supported by PyPI. However, PyPI now supports Markdown as an option, if you set the `long_description_content_type` value in the `setup()` call to `text/markdown` (see https://stackoverflow.com/questions/26737222/how-to-make-pypi-description-markdown-work). 

Markdown is more well known by more people and generally has easier and better support in most editors out of the box. To improve people's contribution experience and make it easier to write documentation, I'd like to switch the README to markdown. An ancillary benefit is that it will show up correctly on the Docker Hub, which expects markdown.

**Comment by Pratham-Dave** [comment]
Hey mplanchard, I would like to work on this issue.

**Comment by ghinks** [comment]
I see that [PR 399](https://github.com/pypiserver/pypiserver/pull/399) is closed. I did not see much wrong with that PR. Do you still want to convert the readme to  md along with associated validations and references? If so I am willing to have a go at it.

**Comment by dee-me-tree-or-love** [comment]
> I see that [PR 399](https://github.com/pypiserver/pypiserver/pull/399) is closed. I did not see much wrong with that PR. Do you still want to convert the readme to  md along with associated validations and references? If so I am willing to have a go at it. @dee-me-tree-or-love 👀 

Hey @ghinks! Sorry for such a long silence - it's been a couple of busy weeks for me. If you are still interested in converting the README - I'd be very happy to receive your PR! :) 

I cancelled the previous attempt (#399) because I had to focus on some other things but of course feel free to see if it can be of any use. Indeed, I still believe that a MD-based README can be somewhat nicer and more welcoming for newer tools. But I'd be also happy with any comments and ideas.  😊 👍

**Comment by ghinks** [comment]
@dee-me-tree-or-love I have [Draft PR Open 503](https://github.com/pypiserver/pypiserver/pull/503) and I have a question. Currently there is a [/bin/check_readme.sh](https://github.com/pypiserver/pypiserver/blob/master/bin/check_readme.sh) that is called from the [ci.yml action](https://github.com/pypiserver/pypiserver/blob/master/.github/workflows/ci.yml#L62) for rst checking. What python based markdown checking/linting tool do you have a preference for?

**Comment by dee-me-tree-or-love** [comment]
Hey @ghinks thanks a lot for picking this up! That's a good question. I stumble on it myself for other Python projects. I know only this tools that's written in Python so far https://github.com/executablebooks/mdformat, and to me it's looking rather good but I never tested it. I'm otherwise more used to the NodeJs-based `markdownlint`. But we could give `mdformat` a try and see if it works for this README. Probably there are other tools out there too though, but we can always swap later. What do you say?

**Comment by ghinks** [comment]
I went with mdformat , it did the trick. A few little things other than updating to markdown were needed.

**Comment by dee-me-tree-or-love** [comment]
Closed by #503 🌟
