### ISSUE TITLE
Is it possible to serve at sub url?

### ISSUE THREAD

**Issue by demonguy** [pypiserver/pypiserver#391]
I want my index url to be xxx.xxx.com/pypi/simple, rather than xxx.xxx.com/simple.
Currently i sestup nginx to redirect xxx.xxx.com/pypi to the pypiserver, however it seems that pypiserver will always serve /simple rather than /pypi/simple, is there any solution?

**Comment by dee-me-tree-or-love** [comment]
Hey @demonguy, sorry for the late response! At this point, I am not aware of a good alternative to what you do currently with the `nginx`, (actually I think that is the right approach in this case and would probably do the same myself). Afaik, `pypiserver` indeed does not support sub-url specifications, but feel free to correct me if I am wrong. I will check it out once again to be sure but I feel that it might be a correct approach at this point. I will keep you posted! :)

**Comment by dee-me-tree-or-love** [comment]
Hey @demonguy, new update here :) I've made a quick check and as far as I see it, `pypiserver` indeed does not support specifying additional sub-routes for the repository. However, since we are using `bottle` as backend, you technically can extend the `pypiserver` using `bottle`'s API. It provides a `mount(...)` function, that allows mounting the applications on top of a parent application by specifying a custom prefix. For example something like this, technically, should work: 
```python
import pypiserver

conf = pypiserver.default_config(
    root = "/tmp/packages"
)
application = pypiserver.app(**conf)

# create a new bottle app to mount the pypiserver to
custom_app = pypiserver.bottle.Bottle()
custom_app.mount('/pypi/', application)
custom_app.run()
```

I've tested and this works on a docker with `python3.9-buster`: 
```bash
$ vim app.py 
# add the contents of the script above into app.py
$ mkdir tmp/packages
$ python3 app.py &
[1] 414
Bottle v0.12.18 server starting up (using WSGIRefServer())...
Listening on http://127.0.0.1:8080/
Hit Ctrl-C to quit.


$ curl localhost:8080/pypi/
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Welcome to pypiserver!</title>
  </head>
  <body>
    <h1>
      Welcome to pypiserver!
    </h1>
    ...
$ curl localhost:8080/pypi/simple
127.0.0.1 - - [16/Nov/2021 19:58:05] "GET /pypi/simple HTTP/1.1" 301 0

$ curl localhost:8080/

127.0.0.1 - - [16/Nov/2021 19:57:06] "GET / HTTP/1.1" 404 720
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 404 Not Found</title>
            ...
```


But it's of course just a single attempt, so any comments and corrections are welcome! But this should be something that can work.  
 
You can read up more about Bottle's mounting here in [their official docs](https://bottlepy.org/docs/dev/tutorial.html#plugins-and-sub-applications) and there's a similar approach described for adding [custom WSGI backend here in our Readme](https://github.com/pypiserver/pypiserver#using-a-different-wsgi-server). Hope this helps! Let me know if it leads you somewhere. 

Otherwise, under some aims for setting up easier plugin implementation and supporting of different backends as a [milestone for 2.0.0](https://github.com/pypiserver/pypiserver/milestone/11). release, I think making this a standard feature of `pypiserver` at this point would be the right decision. I feel this for example would be a great use case for a custom plugin, but it's something worth revisiting in the future!

I will close this issue for now but feel free to reopen if anything ✌️ :)
