### ISSUE TITLE
docker run pypiserver error

### ISSUE THREAD

**Issue by TalentedBastard** [pypiserver/pypiserver#543]
I use docker part in readme to start my pypiserver, however, an exception occurred, it Shows that there is no file named htpasswd.txt, but my dir has this file 

command : 
1.  pip install passlib  and    htpasswd -sc htpasswd.txt <some_username>
2. docker run -p 30011:8080 -v ./htpasswd:/data/.htpasswd pypiserver/pypiserver:latest run -P ./htpasswd.txt ./packages

my dir
![image](https://github.com/pypiserver/pypiserver/assets/51253663/213a728e-55f8-41b9-a6d3-e6876b9bd98a)

error:
![image](https://github.com/pypiserver/pypiserver/assets/51253663/0890a4d3-c10d-42d4-8004-6180551e3735)

**Comment by dee-me-tree-or-love** [comment]
Hello @TalentedBastard! Thanks for submitting the issue and adding the screenshots 👍  If I read it correctly, I'd double check the volume mapping of `htpasswd` to the docker container and its eventual use as an argument. 

When running in docker, as in here:

```bash
pypiserver/pypiserver:latest run -P <HTTPASSWORD_FILE> <PACKAGES_DIR>
```

Both `<HTTPASSWORD_FILE>` and `<PACKAGES_DIR>` should be relative to the files available within the container. So in your case, `<HTTPASSWORD_FILE>` should point to the password file you've added to `/data/.htpasswd` with `-v ./htpasswd:/data/.htpasswd`. And the `<PACKAGES_DIR>` being set to `./packages` should be fine IMO because it will pick it up as a local directory 😇  

So all in all, I think the error you get is that `<HTTPASSWORD_FILE>` set to `./htpasswd.txt` is indeed not existing on the container 🔍  Could you double check if this helps if you make sure you use explicit (or full) container-relative file paths? Let me know if it works, if not I'll be happy to look deeper ✌️

**Comment by dee-me-tree-or-love** [comment]
Hello @TalentedBastard, I hope that you succeeded in solving this problem, but please don't hesitate to comment if not, I'll be happy to look into it deeper. For the time being, since it looks quite silent here I'll close the issue. But feel free to re-open if needed :v:
